### ISSUE TITLE
Recursion: Attacking queens

### ISSUE THREAD

**Issue by Chinmay26** [Apollys/EPI-Variants-Solutions#1]
Compute the smallest number of queens that can be placed to attack every empty on an n x n chessboard. (Queens do not have to attack/defend each other.)

There doesn't seem to be a geometric solution to this.

**Comment by Apollys** [comment]
I'm not sure what you mean.  I have given a solution which I am relatively confident is correct (though I didn't spend the time to formally prove it).  Did you think it was incorrect?

**Comment by Chinmay26** [comment]
Hey, there doesn't seem to be any specific solution to this problem. Here is a an online resource more on this: https://stackoverflow.com/questions/13172730/variant-of-n-queens-algorithm. I didn't explore much but there doesn't seem to exist any mathematical proof to either calculate this.

Great repo btwn :). This is neatly done!

**Comment by Apollys** [comment]
Thanks, wow I totally missed the 3 queens on a 6x6 board solution.  That's so tricky!

That makes this a super lame question then, as there is no optimal algorithm other than brute force... Oh well.  I will update my solution accordingly.
