### ISSUE TITLE
DP: Find a longest alternating subsequence of a given array. (Alternating means a[i] < a[i+1] for even i and a[i] > a[i+1] for odd i.)

### ISSUE THREAD

**Issue by Chinmay26** [Apollys/EPI-Variants-Solutions#3]
There exists couple of solutions (Greedy and D.P.) which can be solved in an efficient O(n) time. IMO, both are really tricky and difficult to solve in an real interview.

Reference: https://leetcode.com/problems/wiggle-subsequence/

**Comment by Apollys** [comment]
Oh man, revisiting this problem I found a pretty straightforward non-DP solution in O(n) time in just a couple minutes.  I was very tired when writing up this whole repo.  Thanks for bringing this to my attention!  I will update the solution writeup!

**Comment by Chinmay26** [comment]
Thanks. This repo has been great help to compare my solutions. 

I am creating these issues hoping this can become a standard reference for the variants in the books.

**Comment by Apollys** [comment]
Updated the write-up!

I appreciate it so much. I went through the whole book writing up these solutions in just a few days, it definitely needs some reviewing and cross-checking.  ^.^
