### ISSUE TITLE
Fuzzy 3-sum problem - given an array and a target sum, find the set of 3 distinct elements in the array that sum to the nearest value to the target sum.

### ISSUE THREAD

**Issue by Chinmay26** [Apollys/EPI-Variants-Solutions#5]
Using sorted_two_sum, we can achieve this in O(N*N)

1. Sort input O(N*logN)
2. For each element, use sorted_two_sum. Using left and right pointers, move towards target while tracking the triplet closest to target.

 Overall: O(N*N)

Same for next one as well.

**Comment by Apollys** [comment]
Edit: nevermind this, I figured out what you were saying now.  This is all wrong haha.

---

So just to clarify, the idea is to precompute an array of all two-sums in sorted order, then reduce the problem to the two-sum problem, correct?

This seems like a good idea, time complexity is reduced to O(N^2) and space complexity is increased to O(N^2) which is pretty much always a good trade.

I don't see the algorithm right off the bat to compute the array of sorted two sums in N^2 time, so I'll have to have a think about that one :D

**Comment by Apollys** [comment]
Oh I see what you're saying now.  No precomputation other than sorting the input array. Makes sense.

I think that algorithm works just fine! I'll write it up.

**Comment by Apollys** [comment]
Finished writing this one up, good insight on the solution. Thanks again!
